# Application
app.url=http://localhost:8081

# Test Credentials
test.email=test@email.com
test.password=password

# Browser
browser=chrome

# Test Data
product.name=Lenovo ThinkPad X1 Carbon
product.price=$1599.00
product.quantity=2
product.subtotal=$3198.00
cart.total=$3198.00